Repository dwyl/hits, pull requests merged in 2021-11, with the labels that each got.

#128 Deploy to Fly.io
  .dockerignore
  .gitignore
  Dockerfile
  assets/.babelrc
  assets/package-lock.json
  assets/package.json
  assets/webpack.config.js
  config/config.exs
  config/dev.exs
  config/prod.exs
  config/prod.secret.exs
  config/runtime.exs
  config/test.exs
  fly.toml
  lib/hits.ex
  lib/hits/release.ex
  lib/hits_web/endpoint.ex
  lib/hits_web/templates/hit/badge_flat_square.svg
  lib/hits_web/templates/layout/app.html.eex
  lib/hits_web/templates/page/index.html.eex
  mix.exs
  mix.lock
  rel/env.bat.eex
  rel/env.sh.eex
  rel/remote.vm.args.eex
  rel/vm.args.eex
Labels: enhancement, awaiting-review, spike, technical

#131 count hits distinct per useragent_id
  .github/workflows/ci.yml
  README.md
  assets/js/app.js
  coveralls.json
  lib/hits/hit.ex
  lib/hits_web/controllers/hit_controller.ex
  test/hits_web/controllers/hit_controller_test.exs
Labels: enhancement, in-review, technical, chore

#133 Add Fly Deploy script to ci.yml for #132
  .github/workflows/ci.yml
Labels: awaiting-review

#136 Micro-update to test Continuous Delivery/Deployment #132
  assets/js/socket.js
  lib/hits_web/templates/page/index.html.eex
Labels: enhancement, awaiting-review, T5m
